name: CI - Streamlit App

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ✅ Run basic Streamlit check
        run: |
          streamlit version

      - name: ✅ Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: ✅ Run Python file syntax check
        run: |
          find . -name "*.py" -exec python -m py_compile {} \;

      - name: ✅ Run basic test (if exists)
        run: |
          if [ -f test_main.py ]; then
            python test_main.py
          else
            echo "No tests found, skipping."
          fi
